# .nosana-ci.yml
nosana:
  description: Nosana NPM Template

global:
  image: node:19

  trigger:
    branch:
      - main

  environment:
    APP_ENV: production

jobs:

  - name: Install Dependencies
    commands:
      - npm ci
    artifacts:
      - name: node_modules
        path: ./node_modules/

  - name: generate docs
    commands:
      - npm run generate
    resources:
      - name: node_modules
        path: ./
    artifacts:
      - name: dist
        path: ./dist/
